# Generated by Django 3.2.7 on 2021-09-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abra_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abramessages',
            name='msg_read',
            field=models.BooleanField(default=False),
        ),
    ]
